"""Well-known landmark aliases that map to stop names."""

# Maps common user terms → possible stop name substrings (normalized)
ALIASES: dict[str, list[str]] = {
    # Metro stations
    "gənclik metrosu": ["gənclik m/st"],
    "gənclik metro": ["gənclik m/st"],
    "gənclik": ["gənclik m/st"],
    "28 may metrosu": ["28 may m/st"],
    "28 may metro": ["28 may m/st"],
    "28 may": ["28 may m/st"],
    "sahil metrosu": ["sahil m/st"],
    "sahil metro": ["sahil m/st"],
    "koroğlu metrosu": ["koroğlu m/st"],
    "koroğlu metro": ["koroğlu m/st"],
    "koroğlu": ["koroğlu m/st"],
    "əhmədli metrosu": ["əhmədli m/st"],
    "əhmədli metro": ["əhmədli m/st"],
    "əhmədli": ["əhmədli m/st"],
    "nərimanov metrosu": ["nərimanov m/st"],
    "nərimanov metro": ["nərimanov m/st"],
    "nərimanov": ["nərimanov m/st"],
    "memar əcəmi metrosu": ["memar əcəmi m/st"],
    "memar əcəmi metro": ["memar əcəmi m/st"],
    "memar əcəmi": ["memar əcəmi m/st"],
    "nizami metrosu": ["nizami m/st"],
    "nizami metro": ["nizami m/st"],
    "dərnəgül metrosu": ["dərnəgül m/st"],
    "dərnəgül metro": ["dərnəgül m/st"],
    "dərnəgül": ["dərnəgül m/st"],
    "həzi aslanov metrosu": ["həzi aslanov m/st"],
    "həzi aslanov metro": ["həzi aslanov m/st"],
    "həzi aslanov": ["həzi aslanov m/st"],
    "avtovağzal metrosu": ["avtovağzal m/st"],
    "avtovağzal metro": ["avtovağzal m/st"],
    "avtovağzal": ["avtovağzal m/st"],
    "xalqlar dostluğu metrosu": ["xalqlar dostluğu m/st"],
    "xalqlar dostluğu metro": ["xalqlar dostluğu m/st"],
    "xalqlar dostluğu": ["xalqlar dostluğu m/st"],
    "neftçilər metrosu": ["neftçilər m/st"],
    "neftçilər metro": ["neftçilər m/st"],
    "neftçilər": ["neftçilər m/st"],
    "ulduz metrosu": ["ulduz m/st"],
    "ulduz metro": ["ulduz m/st"],
    "ulduz": ["ulduz m/st"],
    "bakmil metrosu": ["bakmil m/st"],
    "bakmil metro": ["bakmil m/st"],
    "bakmil": ["bakmil m/st"],
    "içərişəhər metrosu": ["içərişəhər m/st"],
    "içərişəhər metro": ["içərişəhər m/st"],
    "içərişəhər": ["içərişəhər m/st"],
    "elmlər akademiyası metrosu": ["elmlər akademiyası m/st"],
    "elmlər akademiyası metro": ["elmlər akademiyası m/st"],
    "elmlər akademiyası": ["elmlər akademiyası m/st"],
    "inşaatçılar metrosu": ["inşaatçılar m/st"],
    "inşaatçılar metro": ["inşaatçılar m/st"],
    "inşaatçılar": ["inşaatçılar m/st"],
    "20 yanvar metrosu": ["20 yanvar m/st"],
    "20 yanvar metro": ["20 yanvar m/st"],
    "cəfər cabbarlı metrosu": ["cəfər cabbarlı m/st"],
    "cəfər cabbarlı metro": ["cəfər cabbarlı m/st"],
    # ASCII variants (user types without special chars)
    "genclik": ["gənclik m/st"],
    "koroglu": ["koroğlu m/st"],
    "ehmadli": ["əhmədli m/st"],
    "ahmadli": ["əhmədli m/st"],
    "narimanov": ["nərimanov m/st"],
    "memar ecemi": ["memar əcəmi m/st"],
    "nizami": ["nizami m/st"],
    "dernegul": ["dərnəgül m/st"],
    "hezi aslanov": ["həzi aslanov m/st"],
    "avtovagzal": ["avtovağzal m/st"],
    "neftciler": ["neftçilər m/st"],
    "icherisheher": ["içərişəhər m/st"],
    "icheriseher": ["içərişəhər m/st"],
    "elmler akademiyasi": ["elmlər akademiyası m/st"],
    "insaatcilar": ["inşaatçılar m/st"],
    "cefer cabbarli": ["cəfər cabbarlı m/st"],
}
